/**
 * Imports constants directly from the service for consistency
 */

import {
  ALLOWED_FILE_TYPES,
  ALLOWED_IMAGE_TYPES,
  ALLOWED_VIDEO_TYPES,
  ALLOWED_AUDIO_TYPES,
  ALLOWED_DOCUMENT_TYPES,
  MESSAGE_TYPES,
  MESSAGE_STATUS,
  MESSAGE_DIRECTIONS,
  CONNECTION_STATUS,
  STORAGE_TYPES,
  ERROR_TYPES,
  QUICK_REPLY_TYPES,
  SERVICE_EVENTS,
  DEFAULTS
} from '@weni/webchat-service';

export {
  ALLOWED_FILE_TYPES,
  ALLOWED_IMAGE_TYPES,
  ALLOWED_VIDEO_TYPES,
  ALLOWED_AUDIO_TYPES,
  ALLOWED_DOCUMENT_TYPES,
  MESSAGE_TYPES,
  MESSAGE_STATUS,
  MESSAGE_DIRECTIONS,
  CONNECTION_STATUS,
  STORAGE_TYPES,
  ERROR_TYPES,
  QUICK_REPLY_TYPES,
  SERVICE_EVENTS,
  DEFAULTS
};